package dev.zskn.client.features;

import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.client.MinecraftClient;
import org.lwjgl.glfw.GLFW;

import java.util.Set;

public class BaseXRayFeature extends Feature {

    private static final Set<Block> blockList = Set.of(
            Blocks.DIRT,
            Blocks.COARSE_DIRT,
            Blocks.GRASS_BLOCK,
            Blocks.DEAD_BUSH,
            Blocks.ACACIA_LOG,
            Blocks.BIRCH_LOG,
            Blocks.OAK_LOG,
            Blocks.DARK_OAK_LOG,
            Blocks.JUNGLE_LOG,
            Blocks.MANGROVE_LOG,
            Blocks.SPRUCE_LOG,
            Blocks.AZALEA_LEAVES,
            Blocks.BIRCH_LEAVES,
            Blocks.JUNGLE_LEAVES,
            Blocks.ACACIA_LEAVES,
            Blocks.DARK_OAK_LEAVES,
            Blocks.FLOWERING_AZALEA_LEAVES,
            Blocks.MANGROVE_LEAVES,
            Blocks.SPRUCE_LEAVES,
            Blocks.OAK_LEAVES,
            Blocks.STONE,
            Blocks.SMOOTH_BASALT,
            Blocks.AMETHYST_BLOCK,
            Blocks.AMETHYST_CLUSTER,
            Blocks.BUDDING_AMETHYST,
            Blocks.LARGE_AMETHYST_BUD,
            Blocks.MEDIUM_AMETHYST_BUD,
            Blocks.SMALL_AMETHYST_BUD,
            Blocks.DRIPSTONE_BLOCK,
            Blocks.POINTED_DRIPSTONE,
            Blocks.MOSS_BLOCK,
            Blocks.MOSS_CARPET,
            Blocks.FLOWERING_AZALEA,
            Blocks.GLOW_LICHEN,
            Blocks.SWEET_BERRY_BUSH,
            Blocks.CAVE_VINES,
            Blocks.VINE,
            Blocks.BONE_BLOCK,
            Blocks.BEDROCK,
            Blocks.SUGAR_CANE,
            Blocks.CACTUS,
            Blocks.CAVE_VINES_PLANT,
            Blocks.MAGMA_BLOCK,
            Blocks.POPPY,
            Blocks.DANDELION,
            Blocks.SPORE_BLOSSOM,
            Blocks.AZALEA,
            Blocks.GRASS,
            Blocks.TALL_GRASS,
            Blocks.SEAGRASS,
            Blocks.TALL_SEAGRASS,
            Blocks.GRAVEL,
            Blocks.TUFF,
            Blocks.CALCITE,
            Blocks.BIG_DRIPLEAF,
            Blocks.SMALL_DRIPLEAF,
            Blocks.BIG_DRIPLEAF_STEM,
            Blocks.COAL_ORE,
            Blocks.DEEPSLATE_COAL_ORE,
            Blocks.COPPER_ORE,
            Blocks.DEEPSLATE_COPPER_ORE,
            Blocks.IRON_ORE,
            Blocks.DEEPSLATE_IRON_ORE,
            Blocks.GOLD_ORE,
            Blocks.DEEPSLATE_GOLD_ORE,
            Blocks.NETHER_GOLD_ORE,
            Blocks.DIAMOND_ORE,
            Blocks.DEEPSLATE_DIAMOND_ORE,
            Blocks.LAPIS_ORE,
            Blocks.DEEPSLATE_LAPIS_ORE,
            Blocks.REDSTONE_ORE,
            Blocks.DEEPSLATE_REDSTONE_ORE,
            Blocks.DEEPSLATE,
            Blocks.SAND,
            Blocks.RED_SAND,
            Blocks.CLAY,
            Blocks.DIORITE,
            Blocks.ANDESITE,
            Blocks.GRANITE,
            Blocks.TERRACOTTA,
            Blocks.ORANGE_TERRACOTTA,
            Blocks.LIGHT_GRAY_TERRACOTTA,
            Blocks.WHITE_TERRACOTTA,
            Blocks.RED_TERRACOTTA,
            Blocks.BROWN_TERRACOTTA,
            Blocks.SANDSTONE,
            Blocks.RED_SANDSTONE,
            Blocks.OXEYE_DAISY,
            Blocks.ROSE_BUSH,
            Blocks.LILY_OF_THE_VALLEY,
            Blocks.LILY_PAD,
            Blocks.FERN,
            Blocks.BAMBOO,
            Blocks.COCOA,
            Blocks.PODZOL,
            Blocks.MYCELIUM,
            Blocks.BRAIN_CORAL,
            Blocks.BRAIN_CORAL_BLOCK,
            Blocks.BRAIN_CORAL_FAN,
            Blocks.BRAIN_CORAL_WALL_FAN,
            Blocks.BUBBLE_CORAL,
            Blocks.BUBBLE_CORAL_BLOCK,
            Blocks.BUBBLE_CORAL_FAN,
            Blocks.BUBBLE_CORAL_WALL_FAN,
            Blocks.FIRE_CORAL,
            Blocks.FIRE_CORAL_BLOCK,
            Blocks.FIRE_CORAL_FAN,
            Blocks.FIRE_CORAL_WALL_FAN,
            Blocks.TUBE_CORAL,
            Blocks.TUBE_CORAL_BLOCK,
            Blocks.TUBE_CORAL_FAN,
            Blocks.TUBE_CORAL_WALL_FAN,
            Blocks.HORN_CORAL,
            Blocks.HORN_CORAL_BLOCK,
            Blocks.HORN_CORAL_FAN,
            Blocks.HORN_CORAL_WALL_FAN,
            Blocks.MUSHROOM_STEM,
            Blocks.BROWN_MUSHROOM_BLOCK,
            Blocks.BROWN_MUSHROOM,
            Blocks.RED_MUSHROOM_BLOCK,
            Blocks.RED_MUSHROOM,
            Blocks.BLUE_ORCHID,
            Blocks.MANGROVE_ROOTS,
            Blocks.MUDDY_MANGROVE_ROOTS,
            Blocks.MUD,
            Blocks.ALLIUM,
            Blocks.AZURE_BLUET,
            Blocks.ORANGE_TULIP,
            Blocks.PINK_TULIP,
            Blocks.RED_TULIP,
            Blocks.WHITE_TULIP,
            Blocks.CORNFLOWER,
            Blocks.PUMPKIN,
            Blocks.NETHERRACK,
            Blocks.SOUL_SAND,
            Blocks.SOUL_SOIL,
            Blocks.BASALT,
            Blocks.GLOWSTONE,
            Blocks.END_STONE,
            Blocks.EMERALD_ORE,
            Blocks.DEEPSLATE_EMERALD_ORE,
            Blocks.NETHER_QUARTZ_ORE,
            Blocks.PACKED_ICE,
            Blocks.SUNFLOWER,
            Blocks.LILAC,
            Blocks.PEONY,
            Blocks.LARGE_FERN,
            Blocks.CHORUS_FLOWER,
            Blocks.CHORUS_PLANT,
            Blocks.NETHER_WART_BLOCK,
            Blocks.WARPED_WART_BLOCK,
            Blocks.BLUE_ICE,
            Blocks.WARPED_STEM,
            Blocks.WARPED_HYPHAE,
            Blocks.WARPED_NYLIUM,
            Blocks.WARPED_FUNGUS,
            Blocks.WARPED_ROOTS,
            Blocks.CRIMSON_STEM,
            Blocks.CRIMSON_HYPHAE,
            Blocks.CRIMSON_NYLIUM,
            Blocks.CRIMSON_FUNGUS,
            Blocks.SHROOMLIGHT,
            Blocks.WEEPING_VINES,
            Blocks.WEEPING_VINES_PLANT,
            Blocks.TWISTING_VINES,
            Blocks.TWISTING_VINES_PLANT,
            Blocks.CRIMSON_ROOTS,
            Blocks.BEE_NEST,
            Blocks.ANCIENT_DEBRIS,
            Blocks.BLACKSTONE,
            Blocks.POWDER_SNOW,
            Blocks.ROOTED_DIRT,
            Blocks.HANGING_ROOTS,
            Blocks.RAW_COPPER_BLOCK,
            Blocks.SNOW,
            Blocks.SNOW_BLOCK,
            Blocks.OBSIDIAN,
            Blocks.KELP,
            Blocks.KELP_PLANT
    );
    public BaseXRayFeature() {
        super("BaseXRay", GLFW.GLFW_KEY_O);
    }

    @Override
    public void onClientTick(MinecraftClient client) {
        if (keybind.wasPressed()) {
            if (Features.XRay.toggle) {
                return;
            }
            toggle = !toggle;
            client.worldRenderer.reload();
        }
    }

    public static boolean isBaseBlock(Block block) {
        return !blockList.contains(block);
    }
}
